name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports: ["5432:5432"]

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      WORK_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DEDALUS_API_KEY: ${{ secrets.DEDALUS_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm exec prisma db push --skip-generate --force-reset
      - run: pnpm test
